# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 500a2681937376fc1ddd7ac02ecd68f5304a0d1a35e7ae196b681d9bccf5b74e01e884c7f4b5e9e5e0d4e892b10a4db81ab44baae3d9bca882fefec6463feea2

test:
  secret_key_base: 7351dc75be5e09fcc086a56e0433f5cacc5a3c3272bc7ba3371012458d8c07861a5a832b3bdc413513f9a0a3b41f0d899cfffdd9c1f5756ccdf42e7d396947ba

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
